### ISSUE TITLE
kameleon gets stuck when using pipes

### ISSUE THREAD

**Issue by camilo1729** [oar-team/kameleon#18]
With the new recipes based on either QEMU or virtualbox , Kameleon gets stuck when using pipes.

---
extend: qemu/debian7-amd64.yaml

global:
    # You can see the base template `qemu/debian7-amd64.yaml.yaml` to know the
    # variables that you can override

bootstrap:
  - "@base"
  - testing_pipe:
    - first_pipe:
      - local2out:
          - /tmp/hello
          - /tmp/hello
setup:
  - "@base"

export:
  - "@base"

with the previous recipe Kameleon gets stuck

**Comment by mickours** [comment]
This have been fix with the new bash execution mechanism since 2.4.0
