### ISSUE TITLE
Incremental Snapshotting (Example)

### ISSUE THREAD

**Issue by alessiogambi** [oar-team/kameleon#47]
Is it possible to use Kameleon to create incremental snapshots of QEMU images? If this is the case, how? Can you provide a focused example (e.g., in the FAQ) to illustrate it?
Note: For "incremental snapshots" I mean creating a new virtual starting from a previously configured one by executing additional steps on it, and possibly by extending the "parent" receipt using inheritance.

**Comment by SalemHarrache** [comment]
Hi,

I'm not sure to understand what you mean by "incremental snapshot".

So let me know if I'm wrong: you want to reuse an image generated by a parent recipe to specialize it in the daughter recipe?

It is not possible to do so directly with the recipe inheritance. The inheritance allows you to reuse the steps (input) in various recipes, but not to reuse the images (output). To do so, it is best to use the persistent cache.

However, it is possible to manually specialize an image in another recipe, by changing the steps in the ``bootstrap`` part to boot on a specific image rather than creating a new one.

Alternatively, you can use the Kameleon checkpoints to manually export various images (corresponding to some specific steps) from the same recipe.

To do so, you will first need to activate the Kameleon checkpoints during the build:
```
$ kameleon build qemu/debian7.yaml --enable-checkpoint
```
Once the build is complete, you can list the different checkpoints created:
```
$ kameleon build qemu/debian7.yaml --list-checkpoints
The following checkpoints are available for  the recipe 'debian7':
ID           | STEP
-------------|-----------------------------------------------------
6ce8578b8ae0 | setup/configure_apt/configure_source_list
350cabe0f59b | setup/configure_apt/add_contribs_and_nonfree_sources
984f20d909fe | setup/configure_apt/update_repositories
1d4702819a2a | setup/upgrade_system/upgrade_system
b128a1ba498c | setup/install_software/core_packages
4dbd6619eae7 | setup/configure_kernel/configure_kernel
153b31777e84 | setup/configure_kernel/update_initramfs
f5629c44ffff | setup/install_bootloader/install_extlinux
3548bf476c22 | setup/configure_system/configure_locales
b1a5984f1f45 | setup/configure_system/set_timezone
3de1b228f91b | setup/configure_keyboard/keyboard_config
6ed3a172d30c | setup/configure_network/network_interfaces
74dba1fdd4aa | setup/configure_network/set_hosts
0da76337fd0c | setup/configure_network/set_hostname
20c18aed3755 | setup/kameleon_customization/configure_bashrc
5784df0b7f61 | setup/kameleon_customization/configure_vim
18b2141a3f23 | setup/kameleon_customization/configure_python
67a5286a912e | setup/create_group/create_group
0656adcde66b | setup/create_user/add_user
3806a37c7a29 | setup/create_user/add_to_groups
76a6ea48ea69 | setup/_clean_setup/_clean_2_update_repositories
2d75c0a462ce | setup/_clean_setup/_clean_1_prepare_sshd
```

Each checkpoint is associated to a qemu snapshot.

```
$ qemu-img snapshot -l build/debian7/base_debian7.qcow2
Snapshot list:
ID        TAG                 VM SIZE                DATE       VM CLOCK
1         6ce8578b8ae0           727M 2015-06-21 11:13:48   00:03:06.852
2         350cabe0f59b           726M 2015-06-21 11:14:34   00:03:37.554
3         984f20d909fe           727M 2015-06-21 11:15:22   00:03:46.654
4         1d4702819a2a           755M 2015-06-21 11:26:08   00:04:34.872
5         b128a1ba498c           759M 2015-06-21 11:27:06   00:05:16.383
6         4dbd6619eae7           759M 2015-06-21 11:27:50   00:05:18.550
7         153b31777e84           760M 2015-06-21 11:28:24   00:05:29.852
8         f5629c44ffff           760M 2015-06-21 12:10:15   00:05:30.522
9         3548bf476c22           755M 2015-06-21 12:10:42   00:05:35.121
10        b1a5984f1f45           755M 2015-06-21 12:11:22   00:05:36.997
11        3de1b228f91b           758M 2015-06-21 12:12:01   00:05:43.121
12        6ed3a172d30c           758M 2015-06-21 12:12:39   00:05:45.466
13        74dba1fdd4aa           758M 2015-06-21 12:13:10   00:05:45.596
14        0da76337fd0c           758M 2015-06-21 12:13:45   00:05:45.784
15        20c18aed3755           758M 2015-06-21 12:14:34   00:05:46.463
16        5784df0b7f61           758M 2015-06-21 12:15:09   00:05:52.685
17        18b2141a3f23           758M 2015-06-21 12:15:42   00:06:06.929
18        67a5286a912e           758M 2015-06-21 12:16:15   00:06:33.222
19        0656adcde66b           758M 2015-06-21 12:16:48   00:06:35.475
20        3806a37c7a29           758M 2015-06-21 12:17:18   00:06:35.652
21        76a6ea48ea69           758M 2015-06-21 12:17:56   00:06:37.334
22        2d75c0a462ce           758M 2015-06-21 12:18:30   00:06:37.566
```
You can easily export a snapshot to a new image

```
$ # apply a snapshot
$ qemu-img snapshot -a 18b2141a3f23 build/debian7/base_debian7.qcow2
$ # export to a new image
$ qemu-img convert -p -f qcow2 build/debian7/base_debian7.qcow2 -O qcow2 my_debian7_without_user.qcow2
    (100.00/100%)
```

**Comment by alessiogambi** [comment]
Hi Salem!

Thanks for your reply.
> I'm not sure to understand what you mean by "incremental snapshot".
> 
> So let me know if I'm wrong: you want to reuse an image generated by a parent recipe to specialize it in the daughter recipe?
> 


You are correct.

> It is not possible to do so directly with the recipe inheritance. 
> 

I suspected that; however, with your suggestions I might be able I achieve what I need.

> it is possible to manually specialize an image in another recipe, by changing the steps in the bootstrap part to boot on a specific image rather than creating a new one.
> 

Can you list an example here? I am new to the framework and I am not sure how to do this 'the correct way'

Many thanks !

Best

-- Alessio

**Comment by SalemHarrache** [comment]
Here's an example of recipe using an existing qcow2 image.

The challenge is to inject the ssh keys in the image to be able to connect to
the image in the setup section (see virt-customize)

`debian7_custom.yaml`:
```
#==============================================================================
# vim: softtabstop=2 shiftwidth=2 expandtab fenc=utf-8 cc=81 tw=80
#==============================================================================
#
# DESCRIPTION: Debian 7 (Wheezy) custom system built with qemu-kvm from base
# qcow2 image.
#
#==============================================================================
---
# Enables qemu checkpoint
extend: debian7.yaml
global:
  qemu_image_disk: /path/to/base_disk_to_customize.qcow2

#== Bootstrap the new system and create the 'in_context'
bootstrap:
  - prepare_qemu_custom
  - start_qemu

#== Install and configuration steps
setup:
  - enable_checkpoint
  - install_software:
    - packages: tmux

#== Export the generated appliance in the format of your choice
export:
  - "@base"
```

`steps/bootstrap/prepare_qemu_custom.yaml`:
```
- insecure_ssh_key: $$kameleon_cwd/insecure_ssh_key

- generate_ssh_keys:
  - exec_local: echo -e  'y\n' | ssh-keygen -q -t dsa -f $$insecure_ssh_key -N ''
  - exec_local: cat $$insecure_ssh_key

- inject_ssh_private_key:
  - exec_local: >
      virt-customize \
        --upload $${insecure_ssh_key}.pub:/root/.ssh/authorized_keys -a $${qemu_image_disk} \
        --run-command 'chmod 700 /root/.ssh/' \
        --run-command 'chmod 600 /root/.ssh/authorized_keys' \
        --run-command 'chown -R root:root /root/.ssh' \
  - on_setup_clean:
    - exec_local: >
        virt-customize \
          --delete /root/.ssh/authorized_keys -a $${qemu_image_disk} \

- create_ssh_config:
  - on_checkpoint: redo
  - exec_local: |
      # Find empty SSH forwarding port
      SSH_FWD_PORT=$(__find_free_port 50000 60000)
      echo "SSH forwarding port: $SSH_FWD_PORT"

  - write_local:
    - $$ssh_config_file
    - |
      Host $${kameleon_recipe_name}
      HostName 127.0.0.1
      Port $SSH_FWD_PORT
      User root
      IdentityFile $$insecure_ssh_key
      UserKnownHostsFile /dev/null
      StrictHostKeyChecking no
      PasswordAuthentication no
      IdentitiesOnly yes
      LogLevel FATAL
      ForwardAgent yes
      Compression yes
      Protocol 2
```

To override the variable ``qemu_image_disk`` from CLI, do the following:
```
$ kameleon build qemu/debian7_custom.yaml -g qemu_image_disk:$PWD/debian7.qcow2

...

Step qemu_save_appliance took: 25 secs
Step _clean_export took: 0 secs

Successfully built 'qemu/debian7_custom.yaml'
Total duration : 46 secs
```
That's it, hope this will help :)

Have a nice afternoon,
Salem

**Comment by alessiogambi** [comment]
Dear Salem,

your solution was smooth. Thanks !

> To override the variable qemu_image_disk from CLI, do the following:
> 
> $ kameleon build qemu/debian7_custom.yaml -g qemu_image_disk:$PWD/debian7.qcow2
However, at the moment I am struggling with the to problem of providing values to multiple global variables form the command line.

I cannot find any reference on how override multiple global variables at once.

I tried the following combinations

	-g key:value -g key1:value1

	-g key:value key1:value

without any luck.

Can you suggest something ?

Best

— Alessio 


Dr. Alessio Gambi, PhD
Distributed Systems Group (DSG)
Vienna University of Technology, Austria
alessio.gambi@tuwien.ac.at

**Comment by SalemHarrache** [comment]
Hi,

The second version should be the one working, I will probably add it in the documentation.

To see for yourself, you can test it on this recipe part:

`simple_recipe.yaml`:
```
setup:
  - macrostep:
    - microstep:
      - exec_in: echo $$key1 $$key2
```

```
$ kameleon build touch.yaml -g key1:value1 key2:value2
```

The following should display:

```
[in] The in_context has been initialized
[in] value1 value2
```

Best regards,
Salem
