### ISSUE TITLE
 Error kameleon -> guestfish did not find sda1

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#58]
Using the following export steps: 
export:
  - disable_checkpoint
  - virtualbox_save_appliance:
    - output: $$output
    - save_as_vdi
  - export_g5k

I get an error:

 [local] *stdin*:2: libguestfs: error: zerofree: zerofree_stub: /dev/sda1: No such file or directory
 Starting process: "bash"
 Starting process: "ssh -F /home/neyron/scm/digitalis/kameleon-g5k/build/idall-jessie-x64-std/ssh_config idall-jessie-x64-std -t /bin/bash"
 Starting process: "ssh -F /home/neyron/scm/digitalis/kameleon-g5k/build/idall-jessie-x64-std/ssh_config idall-jessie-x64-std -t /bin/bash"
 Error occured when executing the following command :
 
 > exec_local: echo -e "run\nzerofree /dev/sda1" | LIBGUESTFS_CACHEDIR=/home/neyron/scm/digitalis/kameleon-g5k/build/idall-jessie-x64-std
 >   guestfish -a /home/neyron/scm/digitalis/kameleon-g5k/build/idall-jessie-x64-std/base_idall-jessie-x64-std.vdi

**Comment by mickours** [comment]
I'm closing this because it is recipe related and this recipe is obsolete.
