### ISSUE TITLE
tar.gz compression use gzip => Monothread

### ISSUE THREAD

**Issue by ArthurGarnier** [oar-team/kameleon#72]
When the appliance format tar.gz (maybe other ?) is used, kameleon use gzip (monothreaded program) to compress the image. It could be interesting to use another program (like pigz which is used with the same option than gzip) with multithread support to decrease the compression time.

**Comment by ArthurGarnier** [comment]
Today I tried pigz (ln -s /usr/bin/pigz /bin/gzip) with kameleon, It worked and the generation time has been reduced by 700sec (2000sec => 1300sec) on a 16-CPUs node.

**Comment by npf** [comment]
@ArthurGarnier : it's it a recipe question ? If not, could you provide a pull request ?

**Comment by ArthurGarnier** [comment]
Seems to be a recipe question, in chroot/steps/aliases/export_appliance.py :

   if output.endswith(('tar.gz', 'tgz')):                                                            
        compr = "| %s %s" % (which("gzip"), compression_level_opt)   

This part should test if /usr/bin/pigz exists (return code of $(which pigz) maybe) and use which("pigz") instead of gzip if it's OK.

**Comment by mickours** [comment]
Done in dbfbe33
