### ISSUE TITLE
Using --enable-checkpoint fails the build (virtualbox)

### ISSUE THREAD

**Issue by ArthurGarnier** [oar-team/kameleon#73]
Always on the same step, my build fail both on grid5000 images and debian8 recipe upstream if checkpoints are enabled. 

It's on Step 36 : export/_init_export/_init_0_inject_ssh_private_key :

> --> Running the step...
> [local] [   0.0] Examining the guest ...
> [local] virt-customize: error: libguestfs error: guestfs_launch failed.
> [local] This usually means the libguestfs appliance failed to start or crashed.
> [local] See http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
> [local] or run 'libguestfs-test-tool' and post the *complete* output into a
> [local] bug report or message to the libguestfs mailing list.
> [local] 
> [local] If reporting bugs, run virt-customize with debugging enabled and include 
> [local] the complete output:
> [local] 
> [local]   virt-customize -v -x [...]
> Starting command: "bash"
> Starting command: "ssh -F /root/build/debian8/ssh_config debian8 -t /bin/bash"
> Error occured when executing the following command :
> 
> \> exec_local: |-
> \>   virt-customize \
> \>     -a /root/build/debian8/base_debian8.vmdk \
> \>     --run-command 'diff -U $(wc -l < /root/.ssh/authorized_keys) /root/.ssh/authorized_keys /root/.ssh/.kameleon_authorized_keys | grep '^-' | sed 's/^-//g' > /root/.ssh/safe_authorized_keys' \
> \>     --run-command 'mv /root/.ssh/safe_authorized_keys /root/.ssh/authorized_keys' \
> \>     --run-command 'chmod 600 /root/.ssh/authorized_keys' \
> \>     --delete /root/.ssh/.kameleon_authorized_keys

So I run the command in local context in verbose mode, and I got : 

> (local_context) root@grisou-39: /root/build/debian8 # virt-customize -a /root/build/debian8/base_debian8.vmdk --run-command 'diff -U $(wc -l < /root/.ssh/authorized_keys) /root/.ssh/authorized_keys /root/.ssh/.kameleon_authorized_keys | grep '^-' | sed 's/^-//g' > /root/.ssh/safe_authorized_keys' --run-command 'mv /root/.ssh/safe_authorized_keys /root/.ssh/authorized_keys' --run-command 'chmod 600 /root/.ssh/authorized_keys' --delete /root/.ssh/.kameleon_authorized_keys -v
> [   0.0] Examining the guest ...
> libguestfs: launch: program=virt-customize
> libguestfs: launch: version=1.28.1
> libguestfs: launch: backend registered: unix
> libguestfs: launch: backend registered: uml
> libguestfs: launch: backend registered: libvirt
> libguestfs: launch: backend registered: direct
> libguestfs: launch: backend=direct
> libguestfs: launch: tmpdir=/tmp/libguestfsM8qwNR
> libguestfs: launch: umask=0022
> libguestfs: launch: euid=0
> libguestfs: [00012ms] begin building supermin appliance
> libguestfs: [00012ms] run supermin
> libguestfs: command: run: /usr/bin/supermin
> libguestfs: command: run: \ --build
> libguestfs: command: run: \ --verbose
> libguestfs: command: run: \ --if-newer
> libguestfs: command: run: \ --lock /var/tmp/.guestfs-0/lock
> libguestfs: command: run: \ --copy-kernel
> libguestfs: command: run: \ -f ext2
> libguestfs: command: run: \ --host-cpu x86_64
> libguestfs: command: run: \ /usr/lib/x86_64-linux-gnu/guestfs/supermin.d
> libguestfs: command: run: \ -o /var/tmp/.guestfs-0/appliance.d
> supermin: version: 5.1.11
> supermin: package handler: debian/dpkg
> supermin: acquiring lock on /var/tmp/.guestfs-0/lock
> supermin: if-newer: output does not need rebuilding
> libguestfs: [00027ms] finished building supermin appliance
> libguestfs: [00027ms] begin testing qemu features
> libguestfs: command: run: /usr/bin/qemu-system-x86_64
> libguestfs: command: run: \ -display none
> libguestfs: command: run: \ -help
> libguestfs: command: run: /usr/bin/qemu-system-x86_64
> libguestfs: command: run: \ -display none
> libguestfs: command: run: \ -version
> libguestfs: qemu version 2.1
> libguestfs: command: run: /usr/bin/qemu-system-x86_64
> libguestfs: command: run: \ -display none
> libguestfs: command: run: \ -machine accel=kvm:tcg
> libguestfs: command: run: \ -device ?
> libguestfs: [00214ms] finished testing qemu features
> [00218ms] /usr/bin/qemu-system-x86_64 \
>     -global virtio-blk-pci.scsi=off \
>     -nodefconfig \
>     -enable-fips \
>     -nodefaults \
>     -display none \
>     -cpu host \
>     -machine accel=kvm:tcg \
>     -m 500 \
>     -no-reboot \
>     -rtc driftfix=slew \
>     -no-hpet \
>     -global kvm-pit.lost_tick_policy=discard \
>     -kernel /var/tmp/.guestfs-0/appliance.d/kernel \
>     -initrd /var/tmp/.guestfs-0/appliance.d/initrd \
>     -device virtio-scsi-pci,id=scsi \
>     -drive file=/root/build/debian8/base_debian8.vmdk,cache=writeback,discard=unmap,id=hd0,if=none \
>     -device scsi-hd,drive=hd0 \
>     -drive file=/var/tmp/.guestfs-0/appliance.d/root,snapshot=on,id=appliance,cache=unsafe,if=none \
>     -device scsi-hd,drive=appliance \
>     -device virtio-serial-pci \
>     -serial stdio \
>     -device sga \
>     -chardev socket,path=/tmp/libguestfsM8qwNR/guestfsd.sock,id=channel0 \
>     -device virtserialport,chardev=channel0,name=org.libguestfs.channel.0 \
>     -netdev user,id=usernet,net=169.254.0.0/16 \
>     -device virtio-net-pci,netdev=usernet \
>     -append 'panic=1 console=ttyS0 udevtimeout=6000 no_timer_check acpi=off printk.time=1 cgroup_disable=memory root=/dev/sdb selinux=0 guestfs_verbose=1 guestfs_network=1 TERM=xterm'
> qemu-system-x86_64: -drive file=/root/build/debian8/base_debian8.vmdk,cache=writeback,discard=unmap,id=hd0,if=none: could not open disk image /root/build/debian8/base_debian8.vmdk: VMDK version 3 must be read only
> libguestfs: child_cleanup: 0x1562e80: child process died
> libguestfs: sending SIGTERM to process 10213
> virt-customize: error: libguestfs error: guestfs_launch failed, see earlier 
> error messages
> 
> If reporting bugs, run virt-customize with debugging enabled and include 
> the complete output:
> 
>   virt-customize -v -x [...]
> libguestfs: closing guestfs handle 0x1562e80 (state 0)
> libguestfs: command: run: rm
> libguestfs: command: run: \ -rf /tmp/libguestfsM8qwNR

In "normal" mode, the build finishes successfully. Perhaps I'm wrong but the bug seems coming from Kameleon and not from the recipe. 

Step to reproduce : 

1. kameleon build --enable-checkpoint kameleon-recipes/virtualbox/debian8.yaml

**Comment by mickours** [comment]
Sorry for not responding to this but was not available for this project.
It seems to be a problem with an old version of Qemu that do not support VMDK 3 except in read-only mode. The checkpoint mechanism is using VMDK but without checkpoint you should be able to export the image without problem.

The problem disapaer with the last version of libGuestfs/Qemu so you can also  try to update those tools.

As it is pretty old and not directly related to kameleon I am closing this issue. Don't hesitate to re-open it if you still have a this problem.
