### ISSUE TITLE
Why get the kameleon_helpers from remote, not from a data dir (stored with the steps) ?

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#75]
[local] kameleon-helpers-master/create_appliance.py
[local] kameleon-helpers-master/export_appliance.py
[local] kameleon-helpers-master/export_tar.py
[local] kameleon-helpers-master/has_bootloader.py
[local] kameleon-helpers-master/need_bootloader.py
[local] kameleon-helpers-master/simple_http_server.py

**Comment by mickours** [comment]
Now in kameleon recipes (chroot/steps/data/helpers/README.md) by default since: 36c9376e
